// savage-dice-roller/src/background.js

chrome.action.onClicked.addListener((tab) => {
  if (!tab.id) return;

  const tabId = tab.id;

  // First inject the CSS
  chrome.scripting.insertCSS(
    {
      target: { tabId: tabId },
      files: ["src/styles.css"],
    },
    () => {
      // Then inject the JS (the bundle generated by Bun)
      chrome.scripting.executeScript(
        {
          target: { tabId: tabId },
          files: ["dist/content.js"],
        },
        () => {
          // Finally, send the message to the toggle
          chrome.tabs.sendMessage(tabId, { action: "toggleSavageWorldsUI" });
        },
      );
    },
  );
});
